# Generated by Django 2.0.2 on 2018-02-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(db_column='first_name', max_length=50)),
                ('student_middle_name', models.CharField(blank=True, db_column='middle_name', max_length=50)),
                ('student_last_name', models.CharField(db_column='last_name', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, db_column='date_of_birth')),
                ('date_of_join', models.DateField(blank=True, db_column='date_of_join')),
                ('std_join', models.IntegerField(db_column='std_join')),
                ('std_curr', models.IntegerField(db_column='std_curr')),
                ('std_curr_div', models.CharField(db_column='std_curr_div', max_length=50)),
            ],
        ),
    ]
