# Generated by Django 2.0.2 on 2018-02-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(db_column='date_of_birth', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_join',
            field=models.DateField(db_column='date_of_join', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_middle_name',
            field=models.CharField(db_column='middle_name', max_length=50, null=True),
        ),
    ]
