# Generated by Django 2.0.2 on 2018-02-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180227_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, db_column='date_of_birth', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_join',
            field=models.DateField(blank=True, db_column='date_of_join', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_middle_name',
            field=models.CharField(blank=True, db_column='middle_name', default=None, max_length=50, null=True),
        ),
    ]
