# Generated by Django 2.0.2 on 2018-02-28 15:15

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20180228_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=students.models.student_file_rename),
        ),
    ]
