# Generated by Django 2.0.2 on 2018-02-28 15:43

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.FileField(blank=True, db_column='student_image', default=None, null=True, upload_to=students.models.student_file_rename),
        ),
    ]
