# Generated by Django 2.0.2 on 2018-02-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('dep_id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('dep_name', models.CharField(db_column='dep_name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('des_id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('designation', models.CharField(db_column='designation', max_length=50)),
                ('department_id', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='staffs.department')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('staff_first_name', models.CharField(db_column='first_name', max_length=50)),
                ('staff_middle_name', models.CharField(blank=True, db_column='middle_name', default=None, max_length=50, null=True)),
                ('staff_last_name', models.CharField(db_column='last_name', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, db_column='date_of_birth', default=None, null=True)),
                ('date_of_join', models.DateField(blank=True, db_column='date_of_join', default=None, null=True)),
                ('department_id', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='staffs.department')),
                ('designation_id', models.ForeignKey(db_column='designation_id', on_delete=django.db.models.deletion.CASCADE, to='staffs.designation')),
            ],
        ),
    ]
