# Generated by Django 2.0.2 on 2018-02-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='specialization',
            field=models.CharField(db_column='specialization', default='physics', max_length=50),
            preserve_default=False,
        ),
    ]
