# Generated by Django 2.0.2 on 2018-02-28 15:43

from django.db import migrations, models
import staffs.models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_designation_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_image',
            field=models.FileField(blank=True, db_column='staff_image', default=None, null=True, upload_to=staffs.models.staff_file_rename),
        ),
    ]
